name: release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
jobs:
  release:
    runs-on: macos-14
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Set up GraalVM and Native Image
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 24.0.0
          distribution: graalvm-community
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./jbang export native -Dversion=${{ github.event.inputs.version }} p2e.java
      - name: Assemble
        uses: jreleaser/release-action@2.4.3
        with:
          version: 1.18.0
          setup-java: false
          arguments: assemble
        env:
          JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.version }}
      - name: Release
        uses: jreleaser/release-action@2.4.3
        with:
          version: 1.18.0
          setup-java: false
        env:
          JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GH_PAT }}
